version: '3'
services:
  vagdevi-web:
    image: nginx
    container_name: vagdevi-nginx-cont
    ports:
      - 8086:80
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - vagdevi-db
    networks:
      - vagdevi-network
    command: >
      bash -c "apt update && apt install -y iputils-ping && nginx -g 'daemon off;'"

  vagdevi-db:
    image: mysql
    container_name: vagdevi-mysql-cont
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: my_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - vagdevi-network

networks:
  vagdevi-network:
    driver: bridge
